name: Build game

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      name:
        required: true
        type: string
      output_name:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ inputs.name }} for platform ${{ inputs.platform }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Setup templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/3.4.4.stable ~/.local/share/godot/templates/3.4.4.stable
      - name: Build game
        run: |
          mkdir -v -p "build/${{ inputs.platform }}"
          godot -v --export "${{ inputs.platform }}" "./build/${{ inputs.platform }}/${{ inputs.output_name }}"
      - if: ${{ inputs.platform == 'HTML5' }}
        name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - if: ${{ inputs.platform == 'HTML5' && steps.extract_branch.outputs.branch != 'main' }}
        name: Deploy to GitHub Pages (non-main) 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build/HTML5
          target-folder: ${{ steps.extract_branch.outputs.branch }}
      - if: ${{ inputs.platform == 'HTML5' && steps.extract_branch.outputs.branch == 'main' }}
        name: Deploy to GitHub Pages (main) 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build/HTML5
      - if: ${{ inputs.platform != 'HTML5' }}
        name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ inputs.name }}-${{ steps.extract_branch.outputs.branch }}-${{ inputs.platform }}
          path: "build/${{ inputs.platform }}"