name: PR Builds

on:
  push:
    branches:
      - automation

jobs:
  build-web:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: HTML5
      name: time-lab
      output_name: index.html
  build-windows:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: Windows Desktop
      name: time-lab
      output_name: Time Lab.exe
  build-mac:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: Mac OSX
      name: time-lab
      output_name: Time Lab.zip
  build-linux:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: Linux/X11
      name: time-lab
      output_name: Time Lab.x86_64