name: PR Builds

on:
  push:
    branches:
      - automation

jobs:
  build-web:
    - uses: ./.github/workflows/build-game.yml
      with:
        platform: HTML5
        name: time-lab
    - uses: ./github/workflows/web-deploy.yml
      with:
        name: time-lab
  build-windows:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: Windows Desktop
      name: time-lab