name: Web deploy

on:
  workflow_call:
    name:
      required: true
      type: string

jobs:
  deploy:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ inputs.name }}-${{ steps.extract_branch.outputs.branch }}-HTML5
        path: build/HTML5
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: build/HTML5
        target-folder: ${{ steps.extract_branch.outputs.branch }}